# Generated by Django 4.2.6 on 2023-10-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
