# Generated by Django 5.0 on 2023-12-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_likes_post_key_alter_likes_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(null='true', upload_to='blog/uploads'),
            preserve_default='true',
        ),
    ]
